# CMake generated Testfile for 
# Source directory: C:/Tinycrypto
# Build directory: C:/Tinycrypto/build_host
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_aes256 "C:/Tinycrypto/build_host/Debug/test_aes256.exe")
  set_tests_properties(test_aes256 PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_aes256 "C:/Tinycrypto/build_host/Release/test_aes256.exe")
  set_tests_properties(test_aes256 PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_aes256 "C:/Tinycrypto/build_host/MinSizeRel/test_aes256.exe")
  set_tests_properties(test_aes256 PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_aes256 "C:/Tinycrypto/build_host/RelWithDebInfo/test_aes256.exe")
  set_tests_properties(test_aes256 PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
else()
  add_test(test_aes256 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_chacha20 "C:/Tinycrypto/build_host/Debug/test_chacha20.exe")
  set_tests_properties(test_chacha20 PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_chacha20 "C:/Tinycrypto/build_host/Release/test_chacha20.exe")
  set_tests_properties(test_chacha20 PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_chacha20 "C:/Tinycrypto/build_host/MinSizeRel/test_chacha20.exe")
  set_tests_properties(test_chacha20 PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_chacha20 "C:/Tinycrypto/build_host/RelWithDebInfo/test_chacha20.exe")
  set_tests_properties(test_chacha20 PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
else()
  add_test(test_chacha20 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_curve25519 "C:/Tinycrypto/build_host/Debug/test_curve25519.exe")
  set_tests_properties(test_curve25519 PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_curve25519 "C:/Tinycrypto/build_host/Release/test_curve25519.exe")
  set_tests_properties(test_curve25519 PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_curve25519 "C:/Tinycrypto/build_host/MinSizeRel/test_curve25519.exe")
  set_tests_properties(test_curve25519 PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_curve25519 "C:/Tinycrypto/build_host/RelWithDebInfo/test_curve25519.exe")
  set_tests_properties(test_curve25519 PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
else()
  add_test(test_curve25519 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_hmac "C:/Tinycrypto/build_host/Debug/test_hmac.exe")
  set_tests_properties(test_hmac PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_hmac "C:/Tinycrypto/build_host/Release/test_hmac.exe")
  set_tests_properties(test_hmac PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_hmac "C:/Tinycrypto/build_host/MinSizeRel/test_hmac.exe")
  set_tests_properties(test_hmac PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_hmac "C:/Tinycrypto/build_host/RelWithDebInfo/test_hmac.exe")
  set_tests_properties(test_hmac PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
else()
  add_test(test_hmac NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_secure "C:/Tinycrypto/build_host/Debug/test_secure.exe")
  set_tests_properties(test_secure PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_secure "C:/Tinycrypto/build_host/Release/test_secure.exe")
  set_tests_properties(test_secure PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_secure "C:/Tinycrypto/build_host/MinSizeRel/test_secure.exe")
  set_tests_properties(test_secure PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_secure "C:/Tinycrypto/build_host/RelWithDebInfo/test_secure.exe")
  set_tests_properties(test_secure PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
else()
  add_test(test_secure NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_sha256 "C:/Tinycrypto/build_host/Debug/test_sha256.exe")
  set_tests_properties(test_sha256 PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_sha256 "C:/Tinycrypto/build_host/Release/test_sha256.exe")
  set_tests_properties(test_sha256 PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_sha256 "C:/Tinycrypto/build_host/MinSizeRel/test_sha256.exe")
  set_tests_properties(test_sha256 PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_sha256 "C:/Tinycrypto/build_host/RelWithDebInfo/test_sha256.exe")
  set_tests_properties(test_sha256 PROPERTIES  _BACKTRACE_TRIPLES "C:/Tinycrypto/CMakeLists.txt;46;add_test;C:/Tinycrypto/CMakeLists.txt;0;")
else()
  add_test(test_sha256 NOT_AVAILABLE)
endif()
subdirs("_deps/googletest-build")
